### ISSUE TITLE
a relevant arxiv paper

### ISSUE THREAD

**Issue by hrz2000** [tamlhp/awesome-instruction-editing#10]
Thank you for your great work, we have a very relevant arxiv paper and hope you will cite us in subsequent versions, if possible.

[FreeEdit: Mask-free Reference-based Image Editing with Multi-modal Instruction](https://arxiv.org/abs/2409.18071)

It implements reference-based image editing without the need of the mask with multi-modal editing instructions, further expanding the ability of instruction editing.

![image](https://github.com/user-attachments/assets/06075f95-7b5c-44d4-b015-2ac43ec4e528)

Thank you!

**Comment by tamlhp** [comment]
Big thanks, much appreciated. We will update it in the README and cite it in our subsequent versions.
